# Generated by Django 4.1.3 on 2022-12-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bmw_availabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
