# Generated by Django 4.1.3 on 2022-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ferrari_ford_porsche_delete_user_alter_bmw_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('price', models.TextField()),
                ('caption', models.TextField()),
                ('availabilty', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
