# Generated by Django 4.1.3 on 2022-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_donkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmw',
            name='maker',
            field=models.TextField(default='BMW'),
        ),
        migrations.AddField(
            model_name='donkey',
            name='maker',
            field=models.TextField(default='DONKEY'),
        ),
        migrations.AddField(
            model_name='ferrari',
            name='maker',
            field=models.TextField(default='FERRARI'),
        ),
        migrations.AddField(
            model_name='ford',
            name='maker',
            field=models.TextField(default='FORD'),
        ),
        migrations.AddField(
            model_name='porsche',
            name='maker',
            field=models.TextField(default='PORSCHE'),
        ),
    ]
