# Generated by Django 4.1.3 on 2023-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bmw_maker_donkey_maker_ferrari_maker_ford_maker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.TextField(default='JEEP')),
                ('model', models.TextField()),
                ('price', models.TextField()),
                ('caption', models.TextField()),
                ('availabilty', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
